development:
  adapter: postgresql
  encoding: unicode
  database: altitude_backend_dev
  host: localhost
  pool: 2
  username: rake
  password: rakeuser

test:
  adapter: postgresql
  encoding: unicode
  database: altitude_backend_test
  host: localhost
  pool: 2
  username: rake
  password: rakeuser

production:
  adapter: postgresql
  encoding: unicode
  database: altitude_backend_production
  host: localhost
  pool: 2
  username: rake
  password: rakeuser
